import { describe, expect, it } from 'vitest'

const { appConfigSchema } = await import('../src/module/config/app.schema')
const { summaryParseConfigSchema } = await import('../src/module/config/summaryParse.schema')
const { detailedSummaryParseConfigSchema } = await import('../src/module/config/detailedSummaryParse.schema')
const { transcriptOriginalConfigSchema } = await import('../src/module/config/transcriptOriginal.schema')

describe('app render settings schema', () => {
  it('keeps smart pagination controls in app schema and removes summary parse fields from that module', () => {
    const appKeys = appConfigSchema.fields.map(field => 'key' in field ? field.key : '')

    expect(appKeys).toContain('autoUpdate')
    expect(appKeys).toContain('autoRestartOnInstalledUpdate')
    expect(appKeys).toContain('longTaskCompletionNotify')
    expect(appKeys).toContain('longTaskCompletionNotifyThresholdMs')
    expect(appKeys).toContain('multiPageRender')
    expect(appKeys).toContain('multiPageTriggerAspectRatio')
    expect(appKeys).toContain('multiPageMaxAspectRatio')
    expect(appKeys).toContain('renderImageFormat')
    expect(appKeys).toContain('renderImageQuality')
    expect(appKeys).not.toContain('summaryParse.switch')
    expect(appKeys).not.toContain('summaryParse.keywords')
    expect(appKeys).not.toContain('multiPageHeight')
  })

  it('exposes bilibili push risk cooldown settings from the bilibili schema module', async () => {
    const { bilibiliConfigSchema } = await import('../src/module/config/bilibili.schema')
    const bilibiliKeys = bilibiliConfigSchema.fields.map(field => 'key' in field ? field.key : '')

    expect(bilibiliKeys).toContain('push.riskCooldownEnabled')
    expect(bilibiliKeys).toContain('push.riskCooldownMs')
  })

  it('exposes github external post settings from the github schema module', async () => {
    const { githubConfigSchema } = await import('../src/module/config/github.schema')
    const githubKeys = githubConfigSchema.fields.map(field => 'key' in field ? field.key : '')

    expect(githubKeys).toContain('switch')
    expect(githubKeys).toContain('sendContent')
    expect(githubKeys).toContain('renderCard.enable')
    expect(githubKeys).toContain('renderCard.includeImages')
    expect(githubKeys).toContain('plainTitleReply.switch')
    expect(githubKeys).toContain('plainTitleReply.types')
    expect(githubKeys).toContain('token')
    expect(githubKeys).toContain('proxy.switch')
    expect(githubKeys).toContain('proxy.host')
    expect(githubKeys).toContain('proxy.port')
    expect(githubKeys).toContain('proxy.protocol')
    expect(githubKeys).toContain('proxy.auth.username')
    expect(githubKeys).toContain('proxy.auth.password')
  })

  it('exposes summary parse fields from the dedicated summaryParse schema module', () => {
    const summaryParseKeys = summaryParseConfigSchema.fields.map(field => 'key' in field ? field.key : '')

    expect(summaryParseKeys).toContain('switch')
    expect(summaryParseKeys).toContain('keywords')
    expect(summaryParseKeys).toContain('sendParsedContent')
    expect(summaryParseKeys).toContain('llm.baseUrl')
    expect(summaryParseKeys).toContain('llm.apiKey')
    expect(summaryParseKeys).toContain('llm.model')
    expect(summaryParseKeys).toContain('llm.timeoutMs')
    expect(summaryParseKeys).toContain('llm.retryCount')
    expect(summaryParseKeys).toContain('llm.retryDelayMs')
    expect(summaryParseKeys).toContain('llm.webSearchEnabled')
    expect(summaryParseKeys).toContain('llm.reasoningEnabled')
    expect(summaryParseKeys).toContain('llm.reasoningEffort')
    expect(summaryParseKeys).toContain('asr.mode')
    expect(summaryParseKeys).toContain('asr.whisperCppPath')
    expect(summaryParseKeys).toContain('asr.modelPath')
    expect(summaryParseKeys).toContain('asr.language')
    expect(summaryParseKeys).toContain('asr.threads')
    expect(summaryParseKeys).toContain('asr.ffmpegPath')
    expect(summaryParseKeys).toContain('asr.audioBitrateKbps')
    expect(summaryParseKeys).toContain('asr.maxSegmentMinutes')
    expect(summaryParseKeys).toContain('asr.cloud.baseUrl')
    expect(summaryParseKeys).toContain('asr.cloud.apiKey')
    expect(summaryParseKeys).toContain('asr.cloud.model')
    expect(summaryParseKeys).toContain('asr.cloud.timeoutMs')
    expect(summaryParseKeys).toContain('asr.cloud.retryCount')
    expect(summaryParseKeys).toContain('asr.cloud.retryDelayMs')
    expect(summaryParseKeys.indexOf('asr.cloud.baseUrl')).toBeLessThan(summaryParseKeys.indexOf('asr.videoFrames.enabled'))
  })

  it('exposes detailed summary parse fields from the dedicated detailedSummaryParse schema module', () => {
    const detailedSummaryParseKeys = detailedSummaryParseConfigSchema.fields.map(field => 'key' in field ? field.key : '')
    const reasoningEffortField = detailedSummaryParseConfigSchema.fields.find(
      field => 'key' in field && field.key === 'llm.reasoningEffort'
    )

    expect(detailedSummaryParseKeys).toContain('switch')
    expect(detailedSummaryParseKeys).toContain('keywords')
    expect(detailedSummaryParseKeys).toContain('sendParsedContent')
    expect(detailedSummaryParseKeys).toContain('markdownRender.enabled')
    expect(detailedSummaryParseKeys).toContain('markdownRender.sendTextVersion')
    expect(detailedSummaryParseKeys).toContain('markdownRender.fontSizePx')
    expect(detailedSummaryParseKeys).toContain('markdownRender.multiPageEnabled')
    expect(detailedSummaryParseKeys).toContain('markdownRender.multiPageTriggerAspectRatio')
    expect(detailedSummaryParseKeys).toContain('markdownRender.multiPageMaxAspectRatio')
    expect(detailedSummaryParseKeys).toContain('llm.baseUrl')
    expect(detailedSummaryParseKeys).toContain('llm.apiKey')
    expect(detailedSummaryParseKeys).toContain('llm.model')
    expect(detailedSummaryParseKeys).toContain('llm.timeoutMs')
    expect(detailedSummaryParseKeys).toContain('llm.retryCount')
    expect(detailedSummaryParseKeys).toContain('llm.retryDelayMs')
    expect(detailedSummaryParseKeys).toContain('llm.webSearchEnabled')
    expect(detailedSummaryParseKeys).toContain('llm.reasoningEnabled')
    expect(detailedSummaryParseKeys).toContain('llm.reasoningEffort')
    expect(detailedSummaryParseKeys).toContain('asr.mode')
    expect(detailedSummaryParseKeys).toContain('asr.whisperCppPath')
    expect(detailedSummaryParseKeys).toContain('asr.modelPath')
    expect(detailedSummaryParseKeys).toContain('asr.language')
    expect(detailedSummaryParseKeys).toContain('asr.threads')
    expect(detailedSummaryParseKeys).toContain('asr.ffmpegPath')
    expect(detailedSummaryParseKeys).toContain('asr.audioBitrateKbps')
    expect(detailedSummaryParseKeys).toContain('asr.maxSegmentMinutes')
    expect(detailedSummaryParseKeys).toContain('asr.cloud.baseUrl')
    expect(detailedSummaryParseKeys).toContain('asr.cloud.apiKey')
    expect(detailedSummaryParseKeys).toContain('asr.cloud.model')
    expect(detailedSummaryParseKeys).toContain('asr.cloud.timeoutMs')
    expect(detailedSummaryParseKeys).toContain('asr.cloud.retryCount')
    expect(detailedSummaryParseKeys).toContain('asr.cloud.retryDelayMs')
    expect(detailedSummaryParseKeys.indexOf('asr.cloud.baseUrl')).toBeLessThan(detailedSummaryParseKeys.indexOf('asr.videoFrames.enabled'))
    expect(reasoningEffortField && 'options' in reasoningEffortField ? reasoningEffortField.options : []).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ value: 'xhigh' })
      ])
    )
  })

  it('exposes transcript original fields from the dedicated transcriptOriginal schema module', () => {
    const transcriptOriginalKeys = transcriptOriginalConfigSchema.fields.map(field => 'key' in field ? field.key : '')
    const reasoningEffortField = transcriptOriginalConfigSchema.fields.find(
      field => 'key' in field && field.key === 'llm.reasoningEffort'
    )

    expect(transcriptOriginalKeys).toContain('switch')
    expect(transcriptOriginalKeys).toContain('keywords')
    expect(transcriptOriginalKeys).toContain('sendParsedContent')
    expect(transcriptOriginalKeys).toContain('markdownRender.enabled')
    expect(transcriptOriginalKeys).toContain('markdownRender.sendTextVersion')
    expect(transcriptOriginalKeys).toContain('markdownRender.fontSizePx')
    expect(transcriptOriginalKeys).toContain('markdownRender.multiPageEnabled')
    expect(transcriptOriginalKeys).toContain('markdownRender.multiPageTriggerAspectRatio')
    expect(transcriptOriginalKeys).toContain('markdownRender.multiPageMaxAspectRatio')
    expect(transcriptOriginalKeys).toContain('llm.baseUrl')
    expect(transcriptOriginalKeys).toContain('llm.apiKey')
    expect(transcriptOriginalKeys).toContain('llm.model')
    expect(transcriptOriginalKeys).toContain('llm.timeoutMs')
    expect(transcriptOriginalKeys).toContain('llm.retryCount')
    expect(transcriptOriginalKeys).toContain('llm.retryDelayMs')
    expect(transcriptOriginalKeys).toContain('llm.reasoningEnabled')
    expect(transcriptOriginalKeys).toContain('llm.reasoningEffort')
    expect(transcriptOriginalKeys).toContain('asr.mode')
    expect(transcriptOriginalKeys).toContain('asr.whisperCppPath')
    expect(transcriptOriginalKeys).toContain('asr.modelPath')
    expect(transcriptOriginalKeys).toContain('asr.language')
    expect(transcriptOriginalKeys).toContain('asr.threads')
    expect(transcriptOriginalKeys).toContain('asr.ffmpegPath')
    expect(transcriptOriginalKeys).toContain('asr.audioBitrateKbps')
    expect(transcriptOriginalKeys).toContain('asr.maxSegmentMinutes')
    expect(transcriptOriginalKeys).toContain('asr.cloud.baseUrl')
    expect(transcriptOriginalKeys).toContain('asr.cloud.apiKey')
    expect(transcriptOriginalKeys).toContain('asr.cloud.model')
    expect(transcriptOriginalKeys).toContain('asr.cloud.timeoutMs')
    expect(transcriptOriginalKeys).toContain('asr.cloud.retryCount')
    expect(transcriptOriginalKeys).toContain('asr.cloud.retryDelayMs')
    expect(transcriptOriginalKeys.indexOf('asr.cloud.baseUrl')).toBeLessThan(transcriptOriginalKeys.indexOf('asr.videoFrames.enabled'))
    expect(reasoningEffortField && 'options' in reasoningEffortField ? reasoningEffortField.options : []).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ value: 'xhigh' })
      ])
    )
  })
})
